name: All commits 

on: push
jobs:
  run_shout:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: install
        run: npm i

      - name: run shout
        run: pnpm --filter {packages/website} shout

