name: All commits 

on: push
jobs:
  run_shout:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
    
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2

      - name: install
        run: pnpm i

      - name: run shout
        run: pnpm --filter {packages/website}[HEAD~1] shout

